# -*- mode: yaml; -*-

language: generic

addons:
  apt:
    packages:
      - docker-ce

services: docker

# cache:
#   timeout: 900
#   directories:
#     - $HOME/cache

env:
  - TARGET_IMAGE="alpine-26.1-min"
  - TARGET_IMAGE="alpine-25.3-min"
  - TARGET_IMAGE="alpine-25.2-min"
  - TARGET_IMAGE="ubuntu-26.1-min"
  - TARGET_IMAGE="ubuntu-25.3-min"
  - TARGET_IMAGE="ubuntu-25.2-min"
  - TARGET_IMAGE="ubuntu-25.1-min"
  - TARGET_IMAGE="ubuntu-24.5-min"
  - TARGET_IMAGE="ubuntu-24.4-min"
  - TARGET_IMAGE="ubuntu-24.3-min"
  - TARGET_IMAGE="ubuntu-24.2-min"
  - TARGET_IMAGE="ubuntu-24.1-min"
  - TARGET_IMAGE="ubuntu-23.4-min"
  - TARGET_IMAGE="ubuntu-23.3-min"

install:
  - docker version
  - make .make/build-${TARGET_IMAGE}

# after_success:
#   - |
#     # DOCKER_USERNAME is empty for forked repositories
#     # TRAVIS_PULL_REQUEST is "true" for pull requests
#     # TRAVIS_BRANCH is the current branch or the PR target branch
#     # TRAVIS_PULL_REQUEST_BRANCH is the PR source branch
#     github_branch="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
#     if [[ ! -z "$DOCKER_USERNAME" ]] && [[ "$TRAVIS_PULL_REQUEST" != "true" ]] && \
#        [[ "$github_branch" == "master" ]] || [[ "$github_branch" == "staging-"* ]]; then
#       images push $DOCKER_IMAGES
#     else
#       echo ">>> not pushing"
#     fi
