# -*- mode: yaml; -*-

language: generic

addons:
  apt:
    packages:
      - docker-ce

services: docker

# cache:
#   timeout: 900
#   directories:
#     - $HOME/cache

env:
  - TARGET_IMAGE="alpine-std-26.2"
  - TARGET_IMAGE="alpine-std-26.1"
  - TARGET_IMAGE="alpine-std-25.3"
  - TARGET_IMAGE="alpine-std-25.2"
  - TARGET_IMAGE="ubuntu-std-26.2"
  - TARGET_IMAGE="ubuntu-std-26.1"
  - TARGET_IMAGE="ubuntu-std-25.3"
  - TARGET_IMAGE="ubuntu-std-25.2"
  - TARGET_IMAGE="ubuntu-std-25.1"
  - TARGET_IMAGE="ubuntu-std-24.5"
  - TARGET_IMAGE="ubuntu-std-24.4"
  - TARGET_IMAGE="ubuntu-std-24.3"
  - TARGET_IMAGE="ubuntu-std-24.2"
  - TARGET_IMAGE="ubuntu-std-24.1"
  - TARGET_IMAGE="ubuntu-std-23.4"
  - TARGET_IMAGE="alpine-min-26.2"
  - TARGET_IMAGE="alpine-min-26.1"
  - TARGET_IMAGE="alpine-min-25.3"
  - TARGET_IMAGE="alpine-min-25.2"
  - TARGET_IMAGE="ubuntu-min-26.2"
  - TARGET_IMAGE="ubuntu-min-26.1"
  - TARGET_IMAGE="ubuntu-min-25.3"
  - TARGET_IMAGE="ubuntu-min-25.2"
  - TARGET_IMAGE="ubuntu-min-25.1"
  - TARGET_IMAGE="ubuntu-min-24.5"
  - TARGET_IMAGE="ubuntu-min-24.4"
  - TARGET_IMAGE="ubuntu-min-24.3"
  - TARGET_IMAGE="ubuntu-min-24.2"
  - TARGET_IMAGE="ubuntu-min-24.1"
  - TARGET_IMAGE="ubuntu-min-23.4"

install:
  - docker version
  - make .make/build-${TARGET_IMAGE}

script:
  - docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
  - make .make/push-${TARGET_IMAGE}

# after_success:
#   - |
#     # DOCKER_USERNAME is empty for forked repositories
#     # TRAVIS_PULL_REQUEST is "true" for pull requests
#     # TRAVIS_BRANCH is the current branch or the PR target branch
#     # TRAVIS_PULL_REQUEST_BRANCH is the PR source branch
#     github_branch="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
#     if [[ ! -z "$DOCKER_USERNAME" ]] && [[ "$TRAVIS_PULL_REQUEST" != "true" ]] && \
#        [[ "$github_branch" == "master" ]] || [[ "$github_branch" == "staging-"* ]]; then
#       images push $DOCKER_IMAGES
#     else
#       echo ">>> not pushing"
#     fi
