# -*- mode: Dockerfile; -*-

# This program is free software: you can redistribute it and/or modify it
# under the terms of the Affero GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the Affero GNU General Public
# License for more details.
#
# You should have received a copy of the Affero GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM alpine:3.9 as dev

RUN apk update && apk upgrade
RUN apk add alpine-sdk

{{^min}}
RUN apk add gtk+3.0-dev
RUN apk add libcanberra-gtk3
{{/min}}
RUN apk add ncurses-dev

RUN apk add autoconf
RUN apk add automake
RUN apk add texinfo

RUN apk add gawk
RUN apk add openssh-client
RUN apk add gnupg
RUN apk add gnutls-dev

RUN apk add paxmark

{{^min}}
RUN apk add libxml2-dev
RUN apk add libjpeg-turbo-dev
RUN apk add libpng-dev
RUN apk add librsvg-dev
RUN apk add libxaw-dev
RUN apk add giflib-dev
RUN apk add tiff-dev

RUN apk add dpkg-dev
RUN apk add gconf-dev
RUN apk add pango-dev
RUN apk add alsa-lib-dev
{{/min}}

WORKDIR /opt
RUN curl -vLO http://git.savannah.gnu.org/cgit/emacs.git/snapshot/emacs-{{version}}.tar.gz && \
        tar xvf emacs-{{version}}.tar.gz && \
        mv -v emacs-{{version}} emacs && \
        rm -rf emacs-26.1.tar.gz

WORKDIR /opt/emacs

RUN if [ -d patches ]; then git apply patches/*; fi && \
    ./autogen.sh && \
    ./configure && \
    make -j install

CMD ["emacs"]

# ------------------------------------------------------------

FROM alpine:3.9

RUN apk update && apk upgrade
{{^min}}
RUN apk add gtk+3.0
RUN apk add libcanberra-gtk3
{{/min}}

RUN apk add curl
RUN apk add gnupg
RUN apk add openssh-client

{{^min}}
RUN apk add librsvg
RUN apk add libxpm
RUN apk add giflib
RUN apk add tiff

RUN apk add desktop-file-utils

RUN apk add gconf
RUN apk add alsa-lib
{{/min}}

COPY --from=0 /usr/local /usr/local

CMD ["emacs"]
