# -*- mode: Dockerfile; -*-

# This program is free software: you can redistribute it and/or modify it
# under the terms of the Affero GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the Affero GNU General Public
# License for more details.
#
# You should have received a copy of the Affero GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#

# Image from this Dockerfile tagged as ["ubuntu-26.1-min" "26.1-min"]

FROM ubuntu:12.04 as dev
RUN apt-get update
RUN apt-get install -y build-essential

RUN apt-get install -y libncurses-dev

RUN apt-get install -y autoconf
RUN apt-get install -y automake
RUN apt-get install -y texinfo
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y gnupg
RUN apt-get install -y openssh-client
RUN apt-get install -y libgnutls-dev

RUN apt-get install -y libdbus-1-dev

RUN rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN curl -vLO https://ftp.gnu.org/pub/gnu/emacs/emacs-26.1.tar.gz && \
tar xf emacs-26.1.tar.gz && \
mv -v emacs-26.1 emacs && \
rm emacs-26.1.tar.gz

WORKDIR /opt/emacs
RUN ./configure --with-crt-dir=/usr/lib/x86_64-linux-gnu
RUN make bootstrap
RUN make install

# ------------------------------------------------------------

FROM ubuntu:12.04

RUN apt-get update

RUN apt-get install -y libncurses5

RUN apt-get install -y curl
RUN apt-get install -y gnupg
RUN apt-get install -y gpm
RUN apt-get install -y libgnutls26
RUN apt-get install -y libsm6
RUN apt-get install -y openssh-client
RUN apt-get install -y texinfo

RUN rm -rf /var/lib/apt/lists/*

COPY --from=0 /usr/local /usr/local

CMD ["emacs"]
