# -*- mode: makefile; -*-

all:

TAGS :=
{{#data}}
TAGS  += {{id}}
{{/data}}

DIRS := .make

##################################################

all: build

build: $(TAGS:%=.make/build-%)
	@:

push: build
	docker push conao3/po4a:$(TAG)

##############################

.make/build-%: Dockerfiles/Dockerfile-% $(DIRS)
	docker image build -t conao3/emacs:$* -f $< .
	docker container run -it conao3/emacs:$* emacs --version
	docker container run -it conao3/emacs:$* emacs --batch --eval "(print emacs-version)"
	touch $@

# docker tag conao3/emacs:{{id}} conao3/emacs:{{new_id}}

{{#data}}
.make/push-{{id}}: .make/build-{{id}}
	docker push conao3/emacs:{{id}}
{{/data}}

##################################################

$(DIRS):
	mkdir -p $@

disable-aslr:
	echo 0 > /proc/sys/kernel/randomize_va_space

enable-aslr:
	echo 2 > /proc/sys/kernel/randomize_va_space
